version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: always

  agent-service:
    build: .
    container_name: agent-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
